# -*- coding: utf-8 -*-
"""
Created on Wed Apr  3 09:55:21 2024

@author: Andres Cremades Botella

Folder structure for the problem: folders and files for the flow fields, structures and shaps. Parameters:
    - uvw_folder        : Folder of the velocity data
    - uvw_file          : This file does not contain the file index
    - uvw_folder_tf     : Folder of the velocity data with tensorflow format
    - uvw_folderii_tf   : File of the velocity data with tensorflow format
    - tfrecord_folder   : Folder to the tfrecord files
    - tfrecord_train    : File storing the information of the training tfrecord
    - tfrecord_vali     : File storing the information of the validation tfrecord
    - uvw_folder_tf_ssh : Folder of the velocity data with tensorflow format in external server
    - uvw_folder_temp   : Temporal folder for the velocity data
    - ssh_flag_train    : flag for selecting external server
    - ssh_server        : server for loading the data
    - ssh_username      : user of the server
    - ssh_password      : password of the server
    - data_folder       : Folder for storing the data of the model
    - umean_file        : File for the mean velocity
    - unorm_file        : File for the normalization of the velocity
    - urms_file         : File to save the rms of the velocity
    - umax_file         : File containing the maximum and minimum values of the velocity
    - hist_file         : File to store the training history
    - error_file        : File to store the error of the predictions
    - urmspred_file     : File to save the rms predicted by the model
    - model_folder      : Folder for storing the model
    - model_write       : Name of the model
    - model_read        : Name of a model to read
    - plot_folders      : Folder containing the figures
    - shap_folders      : Folder to store the shap values
    - shap_file         : File to store the shap values
"""

# ----------------------------------------------------------------------------------------------------------------------
# Define the folders and files required for the problem
# ----------------------------------------------------------------------------------------------------------------------
# Data for the flow fields
#     - uvw_folder : Folder of the velocity data
#     - uvw_file   : This file does not contain the file index
# ----------------------------------------------------------------------------------------------------------------------
uvw_folder = '../../P125_21pi_vu/'
uvw_file   = 'P125_21pi_vu.$INDEX$.h5.uvw'

# ----------------------------------------------------------------------------------------------------------------------
# Data for the flow fields in the tensorflow format
#     - uvw_folder_tf     : Folder of the velocity data with tensorflow format
#     - uvw_folderii_tf   : File of the velocity data with tensorflow format
#     - tfrecord_folder   : Folder to the tfrecord files
#     - tfrecord_train    : File storing the information of the training tfrecord
#     - tfrecord_vali     : File storing the information of the validation tfrecord
#     - uvw_folder_tf_ssh : Folder of the velocity data with tensorflow format in external server
#     - uvw_folder_temp   : Temporal folder for the velocity data
#     - ssh_flag_train    : flag for selecting external server
#     - ssh_server        : server for loading the data
#     - ssh_username      : user of the server
#     - ssh_password      : password of the server
# ----------------------------------------------------------------------------------------------------------------------
uvw_folder_tf     = "../../P125_21pi_vu_tf_float32_minmaxnorm/"
uvw_folderii_tf   = 'P125_21pi_vu.$INDEX$'
tfrecord_folder   = '../../tfrecord/'
uvw_folder_tf_ssh = "/scratch/andrescb/explanableturbulentchannel/Project_explainability/P125_21pi_vu_tf_float32_minmaxnorm/"
uvw_folder_temp   = "tmpdata"
ssh_flag_train    = False
ssh_server        = "-"
ssh_username      = "-"
ssh_password      = "-"

# ----------------------------------------------------------------------------------------------------------------------
# Data generated by the code: statistics, training epochs...
#     - data_folder   : Folder for storing the data of the model
#     - umean_file    : File for the mean velocity
#     - unorm_file    : File for the normalization of the velocity
#     - urms_file     : file to save the rms of the velocity
#     - hist_file     : File to store the training history
#     - error_file    : File to store the error in the predictions
#     - umax_file     : File containing the maximum and minimum values of the velocity
#     - urmspred_file : File to save the rms predicted by the model
# ----------------------------------------------------------------------------------------------------------------------
data_folder   = "../../P125_21pi_data/d20240531_Data"
umean_file    = "Umean.txt"
unorm_file    = "norm.txt"
umax_file     = "norm.txt"
urms_file     = "Urms.txt"
hist_file     = "hist.txt"
error_file    = "error.txt"
urmspred_file = "Urms_pred.txt"

# ----------------------------------------------------------------------------------------------------------------------
# Data for the models
#     - model_folder : Folder for storing the model
#     - model_write  : Name of the model
#     - model_read   : Name of a model to load
# ----------------------------------------------------------------------------------------------------------------------
model_folder = "../../P125_21pi_data/d20240531_models"
model_write  = "trained_model.h5"
model_read   = "trained_model.h5"
# ----------------------------------------------------------------------------------------------------------------------
# Data for the plots:
#     - plot_folder : folder to store the plots
# ----------------------------------------------------------------------------------------------------------------------
plot_folder = "../../P125_21pi_data/d20240531_plots"

# ----------------------------------------------------------------------------------------------------------------------
# Data for the uv structures
#     - uv_folder : folder to store the Reynolds stress value
#     - uv_file   : file to store the Reynolds stress value
# ----------------------------------------------------------------------------------------------------------------------
uv_folder = "../../P125_21pi_vu_Qstruc/"
uv_file   = "P125_21pi_vu.$INDEX$.h5.Q"

# ----------------------------------------------------------------------------------------------------------------------
# Data for the SHAP values
#     - shap_folder : folder to store the shap values
#     - shap_file   : file to store the shap values
# ----------------------------------------------------------------------------------------------------------------------
shap_folder = "../../P125_21pi_vu_gradientSHAP_d20240531"
shap_file   = "P125_21pi_vu_nsample$NSAMPLES$.$INDEX$.h5.shap"